wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia" #good practice to use you have more than one apps

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.title, name="title"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("wiki/<str:title>/delete>", views.delete, name="delete"),
    path("search", views.search, name="search"),
    path("newpage", views.newpage, name="newpage"),
    path("randompage", views.randompage, name="randompage")
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
    # path('encyclopedia/', include("encyclopedia.urls"))
]

wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/wiki/encyclopedia/views.py
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from . import util

from django.shortcuts import render
from django import forms
from django.urls import reverse

class searchForm(forms.Form):
    q = forms.CharField(label="entry")

class newPageForm(forms.Form):
    title = forms.CharField(label="title")
    content = forms.CharField(label="description",
            widget=forms.Textarea(attrs={'placeholder': 'Description'}))
    # content = forms.CharField(label="Description") #default widget for CharField is TextInput

class editPageForm(forms.Form):
    # title = forms.CharField(label="title", disabled=True)
    # title = forms.CharField(label="title")
    content = forms.CharField(label="description", widget=forms.Textarea)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": searchForm()
    })


def title(request, title):
    content = util.get_entry(title)
    if content is not None:
        # return util.render_title(request, title, content)
        return render(request, "encyclopedia/title.html", {
            "title": title,
            "content": content,
            "form": searchForm()
        })
    else:
        raise Http404("Entry does not exist")
        # raise Http404() # used in production
    
def search(request):
    query = request.GET.get('q') #entry title if exists
    content = util.get_entry(query)
    if content is not None:
        # return util.render_title(request, query, content)
        return render(request, "encyclopedia/title.html", {
            "title": query,
            "content": content,
            "form": searchForm()
        })
    else:
        entries = util.list_entries()
        have_as_substr = []
        for entry in entries:
            if entry.find(query) != -1:
                have_as_substr.append(entry)
        return render(request, "encyclopedia/search.html", {
            "title": query,
            "entries": have_as_substr,
            "form": searchForm()
        })

def newpage(request):
    if request.method == 'GET':
        return render(request, "encyclopedia/newpage.html", {
                "form": searchForm(),
                "newPageForm": newPageForm()
            })
    elif request.method == 'POST':
        form = newPageForm(request.POST) #taking all the data user submitted
        if form.is_valid():   #https://docs.djangoproject.com/en/3.0/ref/forms/api/#accessing-clean-data
            title = form.cleaned_data["title"]   #dictionary created from the submitted form
            content = util.get_entry(title)
            if content:
                return render(request, "encyclopedia/title.html", {
                    "title": title,
                    "content": content,
                    "form": searchForm()
                })
            else:
                content = form.cleaned_data["content"]
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:index"), {
                    "title": title,
                    "content": content,
                    "form": searchForm()
                })
                # return render(request, "encyclopedia/title.html", {
                #     "title": title,
                #     "content": content,
                #     "form": searchForm()
                # })
        else:
            return render(request, "encyclopedia/newpage.html", {
                "form": searchForm(),
                "newPageForm": form
            })


def edit(request, title):
    if request.method == 'POST':
        form = editPageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("encyclopedia:index"), {
                "title": title,
                "content": content,
                "form": searchForm()
            })
        else:
            raise Http404("eerror while posting") 
    elif request.method == "GET":
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
                "title": title,
                "editPageForm": editPageForm({'title': title, 'content':content}),
                "form": searchForm()
            })
    
def randompage(request):
    title = util.get_rand_entry()
    content = util.get_entry(title)
    return HttpResponseRedirect(reverse("encyclopedia:title", args= [title]), {
                "title": title,
                "content": content,
                "form": searchForm()
            })
    # return render(request, "encyclopedia/title.html", {
    #             "title": title,
    #             "content": content,
    #             "form": searchForm()
    #         })


def delete(request, title):
    util.delete_entry(title)
    return HttpResponseRedirect(reverse("encyclopedia:index"), {
                "form": searchForm()
            })

wiki/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    create new page
{% endblock %}

{% block body %}
    <div id="new_page_form">
        <form action="{% url 'encyclopedia:edit' title %}" method="POST">
        <!-- <form> -->
            {% csrf_token %}
            <div class="new_page_input" class="form-group">
                <div><h3>{{ title }}</h3></div>
                <!-- <label for="id_title">
                    <div><h3>{{ title }}</h3></div>
                </label> -->
            </div>
            <div class="new_page_input" class="form-group">
                <label for="id_content">
                    <div><p>Description:</p></div>
                    {{ editPageForm.content }}
                </label>
            </div>
            <input type="submit" style="margin-top: 20px;" class="btn btn-primary" value="Edit the entry">
        </form>
    </div>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="navigation">
        <h1>All Pages</h1>
    
        <ul>
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <div class="navigation">
                    <h2>Wiki</h2>
                    <form action="{% url 'encyclopedia:search' %}" method="GET">
                        {{form.q}}
                        <!-- <input class="button" type="submit" value="Search"> -->
                        <input class="btn btn-primary" type="submit" value="Search">
                    </form>
                </div>
                <div class="navigation">
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div class="navigation">
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div class="navigation">
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    create new page
{% endblock %}

{% block body %}
    <div id="new_page_form">
        <form action="{% url 'encyclopedia:newpage' %}" method="POST">
            {% csrf_token %}
            <div class="new_page_input" class="form-group">
                <label for="id_title">
                    <div><p>Title:</p></div>
                    {{ newPageForm.title }}
                </label>
            </div>
            <div class="new_page_input" class="form-group">
                <label for="id_content">
                    <div><p>Description:</p></div>
                    {{ newPageForm.content }}
                </label>
            </div>
            <input type="submit" style="margin-top: 20px;" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <div class="entry_not_found">
        <h5>There is no entry for {{ title }}</h5>
        <p>Would you like to add one? <a href="{% url 'encyclopedia:newpage' %}" style="margin-left: 20px;">Create entry for {{ title }}</a></p>
        {% if entries|length != 0 %}
        <!-- While the above example works, be aware that most template filters return strings, so mathematical comparisons using filters will generally not work as you expect. length is an exception. -->
            <h4>Some entries you may be looking for:</h4>
            <ul>
                {% for entry in entries %}
                <!-- <li><a href="wiki/{{ entry }}">{{ entry }}</a></li> -->
                <li><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a></li>
                {% endfor %}
            </ul>
        {% endif%}
    </div>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    
    {{ content | safe}}
    
    <div>
        <a href="{% url 'encyclopedia:edit' title %}">Edit this entry</a>
        <a href="{% url 'encyclopedia:delete' title %}" style="margin-left: 30px;">Delete this entry</a>
    </div>
{% endblock %}